import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;

public class Stock extends javax.swing.JFrame {

    DefaultTableModel dt;
    private javax.swing.JComboBox itemsList;
    private javax.swing.JTable stockTable;
    private javax.swing.JTextField qtyTextField;

    public Stock() {
        initComponents();

        dt =getDt();

        try {
            DBConnect x = new DBConnect();
            String sql =
                    "select p.category,p.rate,p.model,p.company, p.pname, p.product_id " +
                            " from productmaster p";
            ResultSet rs = x.queryReturner(sql);
            itemsList.removeAllItems();
            while (rs.next()) {
                itemsList.addItem(new ProductItem(rs.getString(1),
                                Double.parseDouble(rs.getString(2)),
                                rs.getString(3),
                                rs.getString(4),
                                rs.getString(5),
                                Integer.parseInt(rs.getString(6)),
                                0
                        )
                );
            }
            rs.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Could not load list of items.");

        }


    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stock().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel selectProductLabel = new JLabel();
        itemsList = new javax.swing.JComboBox();
        JLabel enterQtyLabel = new JLabel();
        qtyTextField = new javax.swing.JTextField();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        JButton addItemQtyButton = new JButton();
        JScrollPane jScrollPane1 = new JScrollPane();
        stockTable = new javax.swing.JTable();
        JButton saveButton = new JButton();
        JLabel stockLogoLabel = new JLabel();
        JButton newButton = new JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 100, 0, 0));

        selectProductLabel.setText("Select Product");

        itemsList.setModel(new javax.swing.DefaultComboBoxModel(new String[]{}));

        enterQtyLabel.setText("Enter Qty");

        addItemQtyButton.setText("Add");
        addItemQtyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        stockTable.setModel(getDt());
        jScrollPane1.setViewportView(stockTable);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });


        stockLogoLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        stockLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockin.png"))); // NOI18N

        newButton.setText("New");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(selectProductLabel)
                                                                        .addComponent(enterQtyLabel))
                                                                .addGap(55, 55, 55)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addComponent(qtyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(addItemQtyButton))
                                                                        .addComponent(itemsList, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                                        .addComponent(newButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(stockLogoLabel)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(stockLogoLabel)
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(selectProductLabel)
                                        .addComponent(itemsList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(enterQtyLabel)
                                        .addComponent(qtyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addItemQtyButton))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(76, 76, 76)
                                                .addComponent(saveButton)
                                                .addGap(28, 28, 28)
                                                .addComponent(newButton)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ProductItem selectedItem = (ProductItem)itemsList.getSelectedItem();
        dt.addRow(
                new Object[]{
                        selectedItem.getProductId(),
                        selectedItem.getPName(),
                        qtyTextField.getText()});
        stockTable.setModel(dt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            for (int i = 0; i < dt.getRowCount(); i++) {

                DBConnect x = new DBConnect();
                String sql = "select 1 from stock where product_id = " +
                        dt.getValueAt(i, 0) + ";";

               ResultSet rs = x.queryReturner(sql);
                if(!rs.next()) {
                    sql = "insert into stock values(" +
                            dt.getValueAt(i, 0) + "," +
                            dt.getValueAt(i, 2) + ")";
                    x.queryExecuter(sql);
                }
                else {

                    sql = "update stock set qty = qty+" + dt.getValueAt(i, 2) +
                            " where product_id = " +
                            dt.getValueAt(i, 0) + ";";

                    x.queryExecuter(sql);
                }
                x.commit();
                x.closeConnection();
            }
            JOptionPane.showMessageDialog(this, "Stocks updated successfully.");

        }
        catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       this.dt = getDt();
    }

    private DefaultTableModel getDt(){
        DefaultTableModel dt = new DefaultTableModel();
        dt.addColumn("Product Id");
        dt.addColumn("Product Name");
        dt.addColumn("Qty");
        stockTable.setModel(dt);
        return dt;
    }
}
